name: GitHub Info
on: 
  - workflow_dispatch
jobs:
  info:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v3
# TODO: Any built-in action to leverage SSH key from secret?