name: SourceHut Sync
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  sync-sourcehut:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: webfactory/ssh-agent@v0.5.4
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE }}
      - name: Sync with Sourcehut
        run: |
          git add upstream-sourcehut git@git.sr.ht:~ssmiller25/approximatepi
          git push upstream-sourcehut