name: SourceHut Sync
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  sync-sourcehut:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: "Add Key"
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Sync with Sourcehut
        run: |
          git remote add upstream-sourcehut git@git.sr.ht:~ssmiller25/approximatepi
          git push upstream-sourcehut