name: Codeburg Sync
on: 
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  sync-codeburg:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: "Add Key"
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Sync with Codeberg
        run: |
          git remote add upstream-codeburg git@codeberg.org:ssmiller25/approximatepi.git
          git push upstream-codeburg